version: "3.9"
services:
  web:
    build: ./frontend
    ports:
    - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    environment:
      - DATASOURCE_HOST=db
      - DATASOURCE_PORT=5432
      - DATASOURCE_DB=auctiondb
      - DATASOURCE_USERNAME=auction
      - DATASOURCE_PASSWORD=auction
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=auctiondb
      - POSTGRES_USER=auction
      - POSTGRES_PASSWORD=auction
    ports:
    - "5432:5432"
